### ISSUE TITLE
glob patterns are not working on OSX Yosemite

### ISSUE THREAD

**Issue by alan-agius4** [micromatch/bash-glob#2]
Seems like glob patterns such as "**/*" are not working on OSX Yosemite

it return an empty array
```
node: v6.9.5
npm: 3.10.10
```

My platform is `darwin` however my bash is global not in the below path

`Uncaught Error: spawn /usr/local/bin/bash ENOENT`

**Comment by doowb** [comment]
> my bash is global

What does that mean exactly? Do you have any ideas on how to detect where `bash` is located? I have played around with some ideas in the past, but I didn't find a solution that worked in all environments.

I wonder if we can make this an option and fall back to attempting to detect where `bash` is located if the option isn't provided. Then implementors and users can handle it themselves if necessary.

**Comment by alan-agius4** [comment]
It means that I have if i go to the terminal and try to use bash i am able
too. 

Example:
$ bash

Thus, if from js i try to spawn it, it will be;

spawn('bash', cmd) ...

I quick solution would be try to spawn bash, and on execption try to use the hard coded path you are using.

**Comment by doowb** [comment]
Okay, thanks. I thought that might be what you meant, but I didn't want to make that assumption.

**Comment by jonschlinkert** [comment]
@alan-agius4 are you wrapping `**/*` with quotes?

**Comment by alan-agius4** [comment]
Yes, double quotes.

**Comment by karimsa** [comment]
It seems that bash is installed at `/bin/bash` on OS X Yosemite & up (possibly on older, I can't test that).

This could be solved by doing some type of `which bash` to check the path first. I believe `shelljs` has an implementation that can be used.

I'm saying this because I'm getting this issue as well.
